services:
  - type: web
    name: writeaspeech-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_KEY
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
